# SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
# SPDX-License-Identifier: MIT
---
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: reach,diff,flags,components
  behavior: default
  require_changes: false

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: api
      paths:
        - apps/api/src/**
