---
# SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
# SPDX-License-Identifier: MIT

packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true

# Ensure pnpm version compatibility
engines:
  pnpm: '>=9.15.4'
