// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
// SPDX-License-Identifier: MIT

// Generated by @genshin/game-data-codegen. Do not edit by hand.
// Regenerate with: pnpm --filter @genshin/game-data-codegen generate resonances
//
// Source: https://github.com/DimbreathBot/AnimeGameData at 433284d22ef1a704e9d49ae22fb96cf7a245828e
//   ExcelBinOutput/TeamResonanceExcelConfigData.json
//   TextMap/TextMap_MediumEN.json
// Names and effect text are HoYoverse in-game English, extracted from the
// game client. Bump the commit in tools/game-data-codegen/src/resonances.ts
// to pick up a rebalance.

export const RESONANCE_DATA = {
  'fervent-flames': {
    id: 'fervent-flames',
    name: 'Fervent Flames',
    condition: { trigger: 'PAIR', element: 'Pyro' },
    description: 'Affected by Cryo for 40% less time. Increases ATK by 25%.',
  },
  'soothing-water': {
    id: 'soothing-water',
    name: 'Soothing Water',
    condition: { trigger: 'PAIR', element: 'Hydro' },
    description: 'Affected by Pyro for 40% less time. Increases Max HP by 25%.',
  },
  'impetuous-winds': {
    id: 'impetuous-winds',
    name: 'Impetuous Winds',
    condition: { trigger: 'PAIR', element: 'Anemo' },
    description:
      'Decreases Stamina Consumption by 15%. Increases Movement SPD by 10%. Shortens Skill CD by 5%.',
  },
  'high-voltage': {
    id: 'high-voltage',
    name: 'High Voltage',
    condition: { trigger: 'PAIR', element: 'Electro' },
    description:
      'Affected by Hydro for 40% less time. Superconduct, Overloaded, Electro-Charged, Lunar-Charged, Quicken, Aggravate, or Hyperbloom have a 100% chance to generate an Electro Elemental Particle (CD: 5s).',
  },
  'sprawling-greenery': {
    id: 'sprawling-greenery',
    name: 'Sprawling Greenery',
    condition: { trigger: 'PAIR', element: 'Dendro' },
    description:
      'Elemental Mastery increased by 50. After triggering Burning, Quicken, Bloom, or Lunar-Bloom reactions, all nearby party members gain 30 Elemental Mastery for 6s. After triggering Aggravate, Spread, Hyperbloom, or Burgeon reactions, all nearby party members gain 20 Elemental Mastery for 6s. The durations of the aforementioned effects will be counted independently.',
  },
  'shattering-ice': {
    id: 'shattering-ice',
    name: 'Shattering Ice',
    condition: { trigger: 'PAIR', element: 'Cryo' },
    description:
      'Affected by Electro for 40% less time. Increases CRIT Rate against opponents that are Frozen or affected by Cryo by 15%.',
  },
  'enduring-rock': {
    id: 'enduring-rock',
    name: 'Enduring Rock',
    condition: { trigger: 'PAIR', element: 'Geo' },
    description:
      'Increases shield strength by 15%. Additionally, when characters protected by a shield, or when Moondrifts formed by Lunar-Crystallize reactions are nearby, the following special characteristics will take effect: DMG dealt increased by 15%, dealing DMG to enemies will decrease their Geo RES by 20% for 15s.',
  },
  'protective-canopy': {
    id: 'protective-canopy',
    name: 'Protective Canopy',
    condition: { trigger: 'UNIQUE_ELEMENTS' },
    description: 'All Elemental RES +15%, Physical RES +15%.',
  },
} as const;
