// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
// SPDX-License-Identifier: MIT

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';

import { compareVersions } from '@genshin/game-data';
import genshinDb from 'genshin-db';

import { toKebabCase } from './slug.js';

/** Only sets with 5-star pieces are tracked; the rest are levelling fodder. */
const ENDGAME_RARITY = 5;

export interface GeneratedArtifactSet {
  id: string;
  name: string;
  version: string;
  bonuses: Record<2 | 4, string>;
}

export function buildArtifactSets(): GeneratedArtifactSet[] {
  genshinDb.setOptions({
    queryLanguages: [genshinDb.Language.English],
    resultLanguage: genshinDb.Language.English,
  });

  const names = genshinDb.artifacts('names', { matchCategories: true });
  const sets: GeneratedArtifactSet[] = [];
  const idToName = new Map<string, string>();

  for (const name of names) {
    const record = genshinDb.artifacts(name);
    if (!record?.rarityList.includes(ENDGAME_RARITY)) continue;

    // The single-piece circlet sets (Prayers for Illumination and friends) cap
    // at 4 stars, so anything here without both bonuses is upstream drift.
    if (!record.effect2Pc || !record.effect4Pc) {
      throw new Error(`Artifact set "${record.name}" is missing a 2- or 4-piece bonus`);
    }

    const id = toKebabCase(record.name);
    if (!id) throw new Error(`Artifact set name "${record.name}" produced an empty id`);
    const collision = idToName.get(id);
    if (collision) {
      throw new Error(`Duplicate artifact set id "${id}" from "${collision}" and "${record.name}"`);
    }
    idToName.set(id, record.name);

    sets.push({
      id,
      name: record.name,
      version: record.version,
      bonuses: { 2: record.effect2Pc, 4: record.effect4Pc },
    });
  }

  // Version descending (newest first), then name for stability.
  sets.sort((a, b) => compareVersions(b.version, a.version) || a.name.localeCompare(b.name));

  return sets;
}

function serializeArtifactSet(set: GeneratedArtifactSet): string {
  return [
    '  {',
    `    id: '${set.id}',`,
    `    name: ${JSON.stringify(set.name)},`,
    `    version: '${set.version}',`,
    '    bonuses: {',
    `      2: ${JSON.stringify(set.bonuses[2])},`,
    `      4: ${JSON.stringify(set.bonuses[4])},`,
    '    },',
    '  },',
  ].join('\n');
}

function serializeModule(sets: GeneratedArtifactSet[]): string {
  // REUSE-IgnoreStart
  const header = [
    '// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>',
    '// SPDX-License-Identifier: MIT',
  ];
  // REUSE-IgnoreEnd

  return [
    ...header,
    '',
    '// Generated by @genshin/game-data-codegen. Do not edit by hand.',
    '// Regenerate with: pnpm --filter @genshin/game-data-codegen generate artifacts',
    '',
    'export const ARTIFACT_SET_DATA = [',
    sets.map(serializeArtifactSet).join('\n'),
    '] as const;',
    '',
  ].join('\n');
}

/** Locates the generated module's path inside the `@genshin/game-data` workspace package. */
function resolveGeneratedPath(): string {
  const require = createRequire(import.meta.url);
  const packageJson = require.resolve('@genshin/game-data/package.json');
  return resolve(dirname(packageJson), 'src/artifacts.generated.ts');
}

/**
 * Regenerate `@genshin/game-data`'s `artifacts.generated.ts` from genshin-db.
 * Returns the number of artifact sets written.
 */
export function generateArtifactSets(): number {
  const sets = buildArtifactSets();
  writeFileSync(resolveGeneratedPath(), serializeModule(sets));
  return sets.length;
}
