// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
// SPDX-License-Identifier: MIT

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';

import { compareVersions, ELEMENTS } from '@genshin/game-data';
import type { Element, Rarity, WeaponType } from '@genshin/game-data';
import genshinDb from 'genshin-db';

import { CHARACTER_RELEASE_DATES } from './character-release-dates.js';
import { toKebabCase } from './slug.js';
import { WEAPON_TYPE_BY_GENSHIN_DB } from './weapons.js';

/** Stands in for the homeland genshin-db leaves blank on characters who have none. */
const UNKNOWN_REGION = 'Unknown';

/**
 * Playable characters the roster deliberately omits. Aloy came from a
 * collaboration and can't be pulled or bought like the rest.
 *
 * The Traveler and the Wonderland Manekins are omitted too, but fall out of
 * the `ELEMENT_NONE` filter rather than needing an entry here.
 */
const EXCLUDED_IDS = new Set(['aloy']);

/** Maps genshin-db `elementType` enums to `Element` values. */
const ELEMENT_BY_GENSHIN_DB: Record<string, Element> = {
  ELEMENT_ANEMO: ELEMENTS.ANEMO,
  ELEMENT_CRYO: ELEMENTS.CRYO,
  ELEMENT_DENDRO: ELEMENTS.DENDRO,
  ELEMENT_ELECTRO: ELEMENTS.ELECTRO,
  ELEMENT_GEO: ELEMENTS.GEO,
  ELEMENT_HYDRO: ELEMENTS.HYDRO,
  ELEMENT_PYRO: ELEMENTS.PYRO,
};

export interface GeneratedCharacter {
  id: string;
  name: string;
  element: Element;
  weaponType: WeaponType;
  rarity: Rarity;
  region: string;
  version: string;
  releaseDate: string;
}

export function buildCharacters(): GeneratedCharacter[] {
  genshinDb.setOptions({
    queryLanguages: [genshinDb.Language.English],
    resultLanguage: genshinDb.Language.English,
  });

  const names = genshinDb.characters('names', { matchCategories: true });
  const characters: GeneratedCharacter[] = [];
  const idToName = new Map<string, string>();

  for (const name of names) {
    const record = genshinDb.characters(name);
    // `ELEMENT_NONE` marks the element-borrowing cast — the Traveler and the
    // Wonderland Manekins — who have no fixed element to file them under.
    if (!record || record.elementType === 'ELEMENT_NONE') continue;

    const id = toKebabCase(record.name);
    if (!id) throw new Error(`Character name "${record.name}" produced an empty id`);
    if (EXCLUDED_IDS.has(id)) continue;

    const collision = idToName.get(id);
    if (collision) {
      throw new Error(`Duplicate character id "${id}" from "${collision}" and "${record.name}"`);
    }
    idToName.set(id, record.name);

    const element = ELEMENT_BY_GENSHIN_DB[record.elementType];
    if (!element) throw new Error(`Unknown element "${record.elementType}" for ${record.name}`);

    const weaponType = WEAPON_TYPE_BY_GENSHIN_DB[record.weaponType];
    if (!weaponType) {
      throw new Error(`Unknown weapon type "${record.weaponType}" for ${record.name}`);
    }

    const releaseDate = CHARACTER_RELEASE_DATES[id];
    if (!releaseDate) {
      throw new Error(
        `No release date for "${id}"; add the debut-banner date to CHARACTER_RELEASE_DATES`,
      );
    }

    characters.push({
      id,
      name: record.name,
      element,
      weaponType,
      rarity: record.rarity,
      region: record.region || UNKNOWN_REGION,
      version: record.version,
      releaseDate,
    });
  }

  // 5-star first, then version descending (newest first), then name for stability.
  characters.sort(
    (a, b) =>
      b.rarity - a.rarity || compareVersions(b.version, a.version) || a.name.localeCompare(b.name),
  );

  return characters;
}

function serializeCharacter(character: GeneratedCharacter): string {
  return [
    '  {',
    `    id: '${character.id}',`,
    `    name: ${JSON.stringify(character.name)},`,
    `    element: '${character.element}',`,
    `    weaponType: '${character.weaponType}',`,
    `    rarity: ${character.rarity},`,
    `    region: ${JSON.stringify(character.region)},`,
    `    version: '${character.version}',`,
    `    releaseDate: '${character.releaseDate}',`,
    '  },',
  ].join('\n');
}

function serializeModule(characters: GeneratedCharacter[]): string {
  // REUSE-IgnoreStart
  const header = [
    '// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>',
    '// SPDX-License-Identifier: MIT',
  ];
  // REUSE-IgnoreEnd

  return [
    ...header,
    '',
    '// Generated by @genshin/game-data-codegen. Do not edit by hand.',
    '// Regenerate with: pnpm --filter @genshin/game-data-codegen generate characters',
    '',
    'export const CHARACTER_DATA = [',
    characters.map(serializeCharacter).join('\n'),
    '] as const;',
    '',
  ].join('\n');
}

/** Locates the generated module's path inside the `@genshin/game-data` workspace package. */
function resolveGeneratedPath(): string {
  const require = createRequire(import.meta.url);
  const packageJson = require.resolve('@genshin/game-data/package.json');
  return resolve(dirname(packageJson), 'src/characters.generated.ts');
}

/**
 * Regenerate `@genshin/game-data`'s `characters.generated.ts` from genshin-db.
 * Returns the number of characters written.
 */
export function generateCharacters(): number {
  const characters = buildCharacters();
  writeFileSync(resolveGeneratedPath(), serializeModule(characters));
  return characters.length;
}
