// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
// SPDX-License-Identifier: MIT

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';

export interface GeneratedModule {
  /** Module path relative to the `@genshin/game-data` package root. */
  path: string;
  /** Name of the `as const` array the module exports. */
  exportName: string;
  /** `generate` subcommand that rewrites the module. */
  command: string;
  /** Serialized array elements, one string per record. */
  entries: readonly string[];
}

/**
 * Generators run from their own `dist/`, so generated modules are located
 * through the workspace link rather than relative to this file.
 */
function resolveGeneratedPath(path: string): string {
  const require = createRequire(import.meta.url);
  const packageJson = require.resolve('@genshin/game-data/package.json');
  return resolve(dirname(packageJson), path);
}

function serializeModule({ exportName, command, entries }: GeneratedModule): string {
  // REUSE-IgnoreStart
  const header = [
    '// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>',
    '// SPDX-License-Identifier: MIT',
  ];
  // REUSE-IgnoreEnd

  return [
    ...header,
    '',
    '// Generated by @genshin/game-data-codegen. Do not edit by hand.',
    `// Regenerate with: pnpm --filter @genshin/game-data-codegen generate ${command}`,
    '',
    `export const ${exportName} = [`,
    entries.join('\n'),
    '] as const;',
    '',
  ].join('\n');
}

export function writeGeneratedModule(module: GeneratedModule): void {
  writeFileSync(resolveGeneratedPath(module.path), serializeModule(module));
}
