// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
// SPDX-License-Identifier: MIT

import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';

export interface GeneratedModule {
  /** Module path relative to the `@genshin/game-data` package root. */
  path: string;
  /** Name of the `as const` object the module exports. */
  exportName: string;
  /** `generate` subcommand that rewrites the module. */
  command: string;
  /** Serialized members, one string per record, in roster order. */
  entries: readonly string[];
}

/**
 * Generators run from their own `dist/`, so generated modules are located
 * through the workspace link rather than relative to this file.
 */
export function resolveGeneratedPath(path: string): string {
  const require = createRequire(import.meta.url);
  const packageJson = require.resolve('@genshin/game-data/package.json');
  return resolve(dirname(packageJson), path);
}

/**
 * Indents one record's fields into a member of the emitted object. Nested
 * fields add two spaces of their own.
 *
 * Keying by id is what makes a duplicate a `tsc` error (TS1117) rather than a
 * silent last-wins overwrite. The id is written as a field too, so a record
 * still carries it once read out of the catalogue.
 */
export function serializeEntry(id: string, fields: readonly string[]): string {
  const members = [`id: '${id}',`, ...fields];

  return [`  '${id}': {`, ...members.map((field) => `    ${field}`), '  },'].join('\n');
}

/** Renders the module text, separately from writing it, so it can be asserted on. */
export function renderModule({ exportName, command, entries }: GeneratedModule): string {
  // REUSE-IgnoreStart
  const header = [
    '// SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>',
    '// SPDX-License-Identifier: MIT',
  ];
  // REUSE-IgnoreEnd

  return [
    ...header,
    '',
    '// Generated by @genshin/game-data-codegen. Do not edit by hand.',
    `// Regenerate with: pnpm --filter @genshin/game-data-codegen generate ${command}`,
    '',
    `export const ${exportName} = {`,
    entries.join('\n'),
    '} as const;',
    '',
  ].join('\n');
}

export function writeGeneratedModule(module: GeneratedModule): void {
  writeFileSync(resolveGeneratedPath(module.path), renderModule(module));
}
