---
# SPDX-FileCopyrightText: 2026 Alex Brandt <alunduil@gmail.com>
# SPDX-License-Identifier: MIT

name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches: [develop, 'release/**']
    paths:
      - 'infrastructure/terraform/environments/**'
      - '.github/workflows/terraform-apply.yml'
      - '.github/workflows/terraform-apply-reusable.yml'

permissions:
  contents: read
  id-token: write

jobs:
  core:
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/terraform-apply-reusable.yml
    with:
      environment: core
    secrets: inherit # pragma: allowlist secret

  dev:
    if: github.ref == 'refs/heads/develop'
    needs: core
    uses: ./.github/workflows/terraform-apply-reusable.yml
    with:
      environment: dev
    secrets: inherit # pragma: allowlist secret

  staging:
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: core
    uses: ./.github/workflows/terraform-apply-reusable.yml
    with:
      environment: staging
    secrets: inherit # pragma: allowlist secret
